#variable show_state for shows and their settings (US state)

tup = [('Alabama', [u'Hart of Dixie (set in the fictional town of Bluebell)']),
 ('Alaska',
  [u'Northern Exposure (set in the fictional city of Cicely)',
   u'Men in Trees (set in the fictional town of Elmo)']),
 ('Arkansas', [u'Evening Shade (in Evening Shade)']),
 ('Arizona',
  [u'Alice (set in Phoenix)',
   u'Medium (set in Phoenix)',
   u'The Lying Game (set in Scottsdale)',
   u'Greetings from Tucson (set in Tucson)',
   u'Sons of Tucson (set in Tucson)',
   u'The New Dick Van Dyke Show']),
 ('California',
  [u'24',
   u'240-Robert',
   u'Two and a Half Men',
   u'77 Sunset Strip',
   u'The A-Team',
   u'Adam-12',
   u'ALF (San Fernando Valley)',
   u'Alien Nation',
   u'Almost Perfect',
   u'American Horror Story season one',
   u'Angel',
   u'B. J. and the Bear',
   u'Banyon',
   u'Barnaby Jones',
   u'The Bernie Mac Show',
   u'The Beverly Hillbillies',
   u'Beverly Hills, 90210',
   u'The Big Bang Theory',
   u'Boomtown',
   u'Boston Blackie',
   u'The Brady Bunch',
   u"Burke's Law",
   u'Cannon',
   u"Charlie's Angels",
   u'Chase',
   u'Chico and the Man',
   u'CHiPs',
   u'Chuck',
   u'City of Angels (1976)',
   u'City of Angels (2000)',
   u'Columbo',
   u'The Bill Cosby Show',
   u'Curb Your Enthusiasm',
   u'Cybill',
   u'David Cassidy: Man Under Cover',
   u'The Debbie Reynolds Show',
   u'Diagnosis: Murder',
   u"Doctors' Hospital",
   u'Dragnet',
   u'Dragnet 1967',
   u'Drop Dead Diva (setting is Los Angeles but actually filmed in Atlanta)',
   u'Emergency!',
   u'Entourage',
   u'Enos',
   u'The Fall Guy',
   u'Fastlane',
   u'The Fresh Prince of Bel-Air',
   u'George Lopez',
   u'Get Christie Love!',
   u'Girlfriends',
   u'Hannah Montana (set primarily in the suburb of Malibu)',
   u'Hardcastle and McCormick',
   u"Here's Lucy",
   u'Hunter',
   u"It's a Living",
   u"It's Like, You Know...",
   u'Jake and the Fatman',
   u'Joey',
   u'Knots Landing',
   u'L.A. Firefighters',
   u'L.A. Law',
   u'Laverne & Shirley (moved to the suburb of Burbank in Season 6)',
   u'Law & Order: Los Angeles',
   u'Lou Grant',
   u'The L Word',
   u'Mannix',
   u'Medical Center',
   u'Melrose Place',
   u'Modern Family',
   u'Moesha',
   u'Moonlighting',
   u'Moonlight (TV series)',
   u'Murder One',
   u'My Living Doll',
   u'The Naked Truth',
   u'NCIS: Los Angeles',
   u'New Girl',
   u'Perry Mason',
   u'Police Story',
   u'Private Practice',
   u'Remington Steele',
   u'Robbery Homicide Division',
   u'The Rockford Files',
   u'Room 222',
   u'Sanford and Son',
   u'The Sarah Silverman Program',
   u'Saved by the Bell',
   u'Six Feet Under',
   u'S.W.A.T.',
   u'The Shield',
   u'The Tim Conway Show',
   u'Titans',
   u'Victorious',
   u'V.I.P.',
   u"What's Happening!!",
   u'Whiz Kids',
   u'Zorro',
   u'Arrested Development (set in Newport Beach)',
   u'The O.C.',
   u'Even Stevens',
   u'Eight Is Enough',
   u'The Mentalist',
   u'Simon & Simon',
   u'Drake & Josh',
   u'John from Cincinnati',
   u'Terriers',
   u'About a Boy',
   u'A.N.T. Farm',
   u'Amy Prentiss',
   u'Betas',
   u'Charmed',
   u'Checkmate',
   u'Dante',
   u'Dharma & Greg',
   u'The Division',
   u'The Doris Day Show',
   u'The John Forsythe Show',
   u'Full House',
   u'Girls Club',
   u'Ground Floor',
   u'Hooperman',
   u'Hotel',
   u'House Calls',
   u'Ironside',
   u'Journeyman',
   u'Just Cause',
   u'Looking',
   u'Love is a Many Splendored Thing',
   u'Love on a Rooftop',
   u'McMillian & Wife/McMillan',
   u'Midnight Caller',
   u'Monk',
   u'My Sister Sam',
   u'Nash Bridges',
   u'Party of Five',
   u'Phyllis',
   u'Silicon Valley',
   u'Sliders (each episode featured a different dimension of the shows main setting)',
   u'Suddenly Susan',
   u"That's So Raven",
   u'The Streets of San Francisco',
   u'Too Close for Comfort',
   u'Trapper John, M.D.',
   u'Trauma (TV series)',
   u'Psych',
   u'Santa Barbara',
   u'Baywatch',
   u'Pacific Blue',
   u"Three's Company",
   u'Out of This World (in Carmel)',
   u'The Bionic Woman (in Ojai)',
   u'Hidden Palms (in Palm Springs)',
   u'Workaholics (in Rancho Cucamonga)',
   u'Buffy the Vampire Slayer (set in the fictional city of Sunnydale)',
   u'Zoey 101 (in boarding school set in Southern California)']),
 ('Colorado',
  [u'Dynasty',
   u'Good Luck Charlie',
   u'Last Man Standing',
   u'Mork & Mindy (set in Boulder)',
   u'Community (set in the fictional locale of Greendale, Colorado)',
   u'The Bill Engvall Show (set in Louisville)',
   u'Dr. Quinn, Medicine Woman']),
 ('Connecticut',
  [u'My Wife and Kids',
   u'Bewitched',
   u'I Love Lucy (show moved here late in the series)',
   u'The Lucy\u2013Desi Comedy Hour',
   u"Who's the Boss? (in Fairfield)",
   u'Judging Amy (set in Hartford)',
   u"Gilmore Girls (principally set in the fictional Connecticut town of Star's Hollow)"]),
 ('Florida',
  [u'Austin & Ally',
   u'Burn Notice',
   u'CSI: Miami',
   u"Dave's World",
   u'Dexter',
   u'Empty Nest',
   u'Eve',
   u'Flipper',
   u'The Golden Girls',
   u'The Golden Palace',
   u'Good Morning, Miami',
   u'Grapevine',
   u'Invasion',
   u'Karen Sisco',
   u'Miami Vice',
   u'Nip/Tuck',
   u'Ocean Ave.',
   u'\xbfQu\xe9 Pasa, USA?',
   u'South Beach (1993 TV series; set in the South Beach area of Miami Beach)',
   u'South Beach (2006 TV series; set in South Beach)',
   u'Surfside 6',
   u'T. J. Hooker',
   u'I Dream of Jeannie (set in Cocoa Beach)',
   u'Second Noah (set in Tampa)']),
 ('Georgia',
  [u'Designing Women',
   u'Matlock',
   u'House of Payne',
   u'Meet the Browns',
   u'The Vampire Diaries',
   u'The Walking Dead',
   u'The Dukes of Hazzard (set in fictional Hazzard County)']),
 ('Hawaii',
  [u'Dog the Bounty Hunter',
   u'Hawaii Five-O (1968 version)',
   u'Hawaii Five-0 (2010 version)',
   u'Hawaiian Eye',
   u'Hawaiian Heat',
   u'Magnum, P.I.']),
 ('Indiana',
  [u'Close to Home',
   u'One Day at a Time',
   u'Men Behaving Badly',
   u'Breaking Away (TV series) (set in Bloomington, Indiana, but filmed in Athens, Georgia)',
   u'The Middle',
   u'Parks and Recreation (set in the fictional town of Pawnee)']),
 ('Illinois',
  [u'All About Us',
   u'According to Jim',
   u'Andy Richter Controls the Universe',
   u'Angel Street',
   u'The Bob Newhart Show',
   u'Boss',
   u'Chicago Code',
   u'Chicago Fire',
   u'Chicago Hope',
   u'Crime Story',
   u'Due South',
   u'Early Edition',
   u'E/R',
   u'ER',
   u'Family Matters',
   u'Freddie',
   u'Good Times',
   u'Happy Endings',
   u"It's All Relative",
   u'Joanie Loves Chachi',
   u'Kenan & Kel',
   u'Kolchak: The Night Stalker',
   u'Life with Bonnie',
   u'The Loop',
   u'Love & War',
   u'M Squad',
   u'Married... with Children',
   u'Mike & Molly',
   u'My Big Fat Greek Life',
   u'My Boys',
   u'Once and Again',
   u'Our Private World',
   u'Pepper Dennis',
   u'Perfect Strangers',
   u'Punky Brewster',
   u'Reasonable Doubts',
   u'Roseanne (in the nearby fictional town of Lanford)',
   u'Shake It Up',
   u'Shameless (U.S. version)',
   u'Soul Food',
   u'Special Unit 2',
   u'The Dresden Files (TV series)',
   u'The Good Wife',
   u'The League',
   u'The Steve Harvey Show',
   u'Still Standing',
   u'Tracker',
   u'The Untouchables (1959 TV series)',
   u'The Untouchables (1993 TV series)',
   u'Webster',
   u'What About Joan?']),
 ('Iowa', [u'Julie (set in Sioux City)']),
 ('Kansas',
  [u'Jericho (in the fictional town of Jericho)',
   u'United States of Tara (in Overland Park)',
   u'Smallville (in the fictional town of Smallville)',
   u'Married to the Kellys (principally set in rural Kansas)']),
 ('Kentucky', [u'Justified (TV series) (set in and around Lexington)']),
 ('Louisiana',
  [u'The Adventures of Jim Bowie',
   u'Bourbon Street Beat',
   u"Frank's Place",
   u'The Big Easy (TV series)',
   u'K-Ville',
   u'Longstreet',
   u'Treme',
   u'The Originals',
   u'American Horror Story: Coven',
   u'NCIS: New Orleans',
   u'Duck Dynasty',
   u'The Haunted Hathaways',
   u'The Originals',
   u'True Blood',
   u'True Detective']),
 ('Maine',
  [u"Under The Dome (fictional town of Chester's Mill)",
   u'Once Upon a Time (fictional town of Storybrooke)',
   u'Haven (fictional Maine town)',
   u'Murder, She Wrote (fictional Maine town, filmed in Mendocino, California)']),
 ('Maryland',
  [u'Homicide: Life on the Street',
   u'Hot l Baltimore',
   u'Roc',
   u'The Wire',
   u'The Corner',
   u'Hannibal (TV series)']),
 ('Massachusetts',
  [u'Ally McBeal',
   u'Banacek',
   u'Beacon Hill',
   u"Being Human'",
   u'Boston Common',
   u'Boston Legal',
   u'Boston Public',
   u'Cheers',
   u'Crossing Jordan',
   u'Fringe',
   u'Goodnight, Beantown',
   u'James at 15',
   u'Leverage',
   u'Paul Sand in Friends and Lovers',
   u'The Practice',
   u'Rizzoli & Isles',
   u'Sabrina The Teenage Witch',
   u'Spenser: For Hire',
   u'St. Elsewhere',
   u'The Suite Life of Zack & Cody',
   u'Tru Calling',
   u'Two Guys, a Girl and a Pizza Place',
   u'The Young Lawyers',
   u"Dawson's Creek (In the fictional town of Capeside)",
   u'Wings (in Nantucket)']),
 ('Michigan',
  [u'Detroit 1-8-7',
   u'Home Improvement',
   u'Low Winter Sun',
   u'Martin',
   u'Sister, Sister',
   u'Soul Man',
   u'8 Simple Rules (For Dating My Teenage Daughter) (set in Auburn Hills)']),
 ('Minnesota', [u'The Big C', u'Coach', u'The Mary Tyler Moore Show']),
 ('Missouri',
  [u'Apple Pie',
   u'Kansas City SWAT',
   u'The Legend of Jesse James',
   u'Malcolm & Eddie',
   u'Pulse of the City',
   u'Switched at Birth',
   u'The Soul Man',
   u'AfterMASH',
   u'The Baxters',
   u'Farmer Wants a Wife',
   u'The John Larroquette Show',
   u'Lucas Tanner (set in suburban Webster Groves, Missouri)',
   u'On Our Own',
   u'The Jersey',
   u'W*A*L*T*E*R']),
 ('Nevada',
  [u'CSI: Crime Scene Investigation',
   u'The Defenders (2010 TV series)',
   u'Dr. Vegas',
   u'Las Vegas',
   u'Pawn Stars',
   u'Vega$',
   u'Reno 911!']),
 ('New Jersey',
  [u'Boardwalk Empire (set primarily in Atlantic City)',
   u'Jersey Shore (set in Seaside Heights)']),
 ('New Mexico',
  [u'Breaking Bad',
   u'Better Call Saul',
   u'In Plain Sight',
   u'Roswell (set in Roswell)']),
 ('New York',
  [u'Buffalo Bill',
   u'Jesse',
   u'Off Beat Cinema',
   u'2 Broke Girls',
   u'30 Rock',
   u'All in the Family',
   u'The Morey Amsterdam Show',
   u'Baretta',
   u'Barney Miller',
   u'Becker',
   u'Bosom Buddies',
   u'Brooklyn Bridge',
   u'Brooklyn South',
   u'Busting Loose',
   u'Cagney & Lacey',
   u'Caroline in the City',
   u'Castle',
   u'Cosby',
   u'CSI: NY',
   u'Doc',
   u"Diff'rent Strokes",
   u'Dream On',
   u'East Side/West Side',
   u'The Equalizer',
   u'Everybody Hates Chris',
   u'Everybody Loves Raymond',
   u'Fair Exchange',
   u'Family Affair',
   u'Felicity',
   u'Fired Up',
   u'Fish',
   u'Foley Square',
   u'Friends',
   u'Going My Way',
   u'Gossip Girl',
   u'Grounded for Life',
   u'He & She',
   u'The Honeymooners',
   u'How I Met Your Mother',
   u'I Love Lucy (later moved to Westport, Connecticut)',
   u'The Investigators',
   u'The Jeffersons',
   u'Jessie',
   u'Just Shoot Me!',
   u'Kate & Allie',
   u'The King of Queens',
   u'Kojak',
   u'Law & Order',
   u'Law & Order: Criminal Intent',
   u'Law & Order: Special Victims Unit',
   u'Law & Order: Trial by Jury',
   u'Less Than Perfect',
   u'Living Dolls',
   u'Living Single',
   u'Lotsa Luck',
   u'I Love Lucy',
   u'McCloud',
   u'Mad About You',
   u'Mad Men',
   u'Make Room for Daddy',
   u'Maude',
   u'Michael Hayes',
   u'Miss Match',
   u'The Nanny',
   u'Ned & Stacey',
   u'NewsRadio',
   u'Night Court',
   u'Nurse Jackie',
   u'Mr. and Mrs. North',
   u'N.Y.P.D.',
   u'NYPD Blue',
   u'New York Undercover',
   u'The Odd Couple',
   u'The Patty Duke Show',
   u'Person of Interest',
   u'Rhoda',
   u"Ryan's Hope",
   u'Seinfeld',
   u'Serpico',
   u'Sex and the City',
   u'The Single Guy',
   u'The Sopranos',
   u'Spin City',
   u'Sports Night',
   u'Suits',
   u'Tattingers or Nick & Hillary',
   u'Taxi',
   u'The Ted Knight Show',
   u'Temporarily Yours',
   u'That Girl',
   u'The Thin Man',
   u'Third Watch',
   u'Time of Your Life',
   u'The Dick Van Dyke Show',
   u'The Unusuals',
   u"Veronica's Closet",
   u'Welcome Back, Kotter',
   u'What I Like About You',
   u'White Collar',
   u'Will & Grace',
   u'Without a Trace',
   u'Wizards of Waverly Place',
   'The Facts of Life (in Peekskill)']),
 ('North Carolina',
  [u'The Andy Griffith Show (set in the fictional city of Mayberry)']),
 ('Ohio',
  [u'WKRP in Cincinnati',
   u"Harry's Law",
   u'The Drew Carey Show',
   u'Hot in Cleveland',
   u'Family Ties',
   u'Hope & Faith',
   u'Glee (in the town of Lima)',
   u'3rd Rock from the Sun (in the fictional suburban city of Rutherford, said to be 52 miles outside Cleveland and roughly corresponding with the location of Kent State University)']),
 ('Oklahoma', [u'Saving Grace']),
 ('Oregon',
  [u'Crash and Bernstein',
   u'Grimm',
   u'Hello, Larry',
   u'Leverage',
   u'Life, Unexpected',
   u'Mysterious Ways',
   u'Portlandia']),
 ('Pennsylvania',
  [u'Amen',
   u'American Dreams',
   u'Angie',
   u'Body of Proof',
   u'Boy Meets World',
   u'Brotherly Love',
   u'Brothers',
   u'Cold Case',
   u'Cosby Show',
   u'Hack',
   u"It's Always Sunny in Philadelphia",
   u"Shannon's Deal",
   u'Strong Medicine',
   u"The Goldbergs (set in 1980's Jenkintown)",
   u'thirtysomething',
   u'The Guardian',
   u'Mr. Belvedere (set in suburban Beaver Falls, Pennsylvania)',
   u"Mister Rogers' Neighborhood",
   u'Queer as Folk',
   u'Remember WENN',
   u'Back to You',
   u'Hope and Gloria',
   u'Sullivan & Son',
   u'The Office (US) (in Scranton)']),
 ('Puerto Rico',
  [u'The Flying Nun (the only series to be set in a US territory)']),
 ('Rhode Island',
  [u'Doctor Doctor (1989)',
   u'Providence',
   u'Family Guy (set in the fictional town of Quahog)']),
 ('Texas',
  [u'Dallas',
   u'Walker, Texas Ranger',
   u'The Good Guys (2010)',
   u'Sons of Thunder',
   u'Flo',
   u'Houston Knights',
   u'Outlaws',
   u'Reba',
   u'Cutter to Houston (set at Cutter Community Hospital in the fictional small town of Cutter, sixty miles from Houston)',
   'Friday Night Lights']),
 ('Tennessee', [u'Memphis Beat', u'Nashville']),
 ('Vermont', [u'Newhart']),
 ('Virginia', [u'JAG (the headquarters in seasons 2-10 is in Falls Church)']),
 ('Washington',
  [u'The 4400',
   u'Dark Angel',
   u'Dead Like Me',
   u'Frasier',
   u"Grey's Anatomy",
   u'Harry and the Hendersons',
   u'Here Come the Brides',
   u'iCarly',
   u'John Doe',
   u'The Killing',
   u'Under One Roof',
   u'Wedding Band',
   u'Twin Peaks (set in a fictional town of the same name)']),
 ('Washington, D.C. and the metropolitan area',
  [u'227',
   u'A Man Called Hawk',
   u'The Agency',
   u'The Americans',
   u"All's Fair",
   u'Bones',
   u'Capitol',
   u'Commander in Chief',
   u'Cory in the House',
   u'The Cosby Show',
   u'Criminal Minds',
   u'The District',
   u'E-Ring',
   u'The F.B.I.',
   u'First Monday',
   u'FM',
   u'Get Smart',
   u'Hail to the Chief',
   u'Hearts Afire',
   u'Homeland',
   u'House of Cards',
   u'I Spy',
   u'JAG (in season 2-10, the headquarters moved to Falls Church, Virginia)',
   u'K Street',
   u'Karen',
   u'Lie to Me',
   u'The Lone Gunmen',
   u'Mr. Smith',
   u'Murphy Brown',
   u'NCIS',
   u'Scandal',
   u'Snoops',
   u"That's My Bush!",
   u"That's My Mama",
   u'The West Wing',
   u'The X-Files',
   u'VEEP']),
 ('Wisconsin',
  [u'Happy Days',
   u'Laverne & Shirley (later moved to Burbank, California)',
   u'Step by Step (set in the suburb of Port Washington, Wisconsin)',
   u"That '70s Show (set in the fictional suburban town of Point Place, Wisconsin)"]),
 ('Wyoming', [u'Longmire'])]

li = []
for row in tup:
    li.append(list(row))

show_state = []

for i in range(len(li)):
    for j in range(len(li[i][1])):
        state = []       
        state.append(li[i][1][j].encode('utf-8').split('(')[0].strip())
        state.append(li[i][0].split(' a')[0])
        show_state.append(state)
